export const OWNER_MUTATION = 'owner'
export const NAME_MUTATION = 'name'
export const SYMBOL_MUTATION = 'symbol'
export const DECIMALS_MUTATION = 'decimals'
export const TOTAL_SUPPLY = 'totalSupply'
